const Constants = {
  SHOW_ENTER_MODAL: 'SHOW_ENTER_MODAL',
  HIDE_ENTER_MODAL: 'HIDE_ENTER_MODAL',
  ENTER_MODAL_STATUS: 'ENTER_MODAL_STATUS',

  // SessionConstants
  LOGIN_CURRENT_USER: 'LOGIN_CURRENT_USER',
  RECEIVE_CURRENT_USER: 'RECEIVE_CURRENT_USER',
  LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER'
};

module.exports = Constants;